### ISSUE TITLE
Is this plugin meant to be used in conjunction with vimwiki?

### ISSUE THREAD

**Issue by nomm-dot** [zdszero/vimwiki-markdown#1]
I expected this plugin to be just a fork of vimwiki with markdown treated as the default syntax with all of the features of vimwiki as well as using pandoc to convert. Looking at wiki.vim this package has much less features. Is this meant to be used in conjunction with vimwiki? If so do the specified configs overwrite vimwiki? 

If this plugin is not meant to be used in conjunction with vimwiki how would one do so? Could you add something to the README that answers this question so that users to could take full advantage of both plugins?

**Comment by zdszero** [comment]
No, this plugin is not a fork of vimwiki. It's totally rewritten but uses the similiar user interface as vimwiki.
It's usage is very similiar to vimwiki.
It's not used in conjunction with vimwiki. And it's designed to work with other markdown plugins.

Thanks for your suggestions, I'll add more introduction in the readme and post a more clear video.
